apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-api
  labels:
    app: scraper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-api
  template:
    metadata:
      labels:
        app: scraper-api
    spec:
      containers:
      - name: scraper-api
        image: hyeonghwan/mini-project-api:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-vol
          mountPath: /api/dynamic-vol
      volumes:
      - name: nfs-vol
        nfs:
          server: 192.168.1.10
          path: /nfs_shared/dynamic-vol

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: scraper-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer