FROM python:3.9

RUN pip install --no-cache-dir fastapi uvicorn requests

RUN mkdir -p /api

WORKDIR /api

COPY ./api/app.py ./app.py
COPY ./api/__init__.py ./__init__.py

EXPOSE 80

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]